const packagePrivateReducers = [
  'RNMO_DDP_CONNECTED', 
  'RNMO_RESTORED', 
  'RNMO_CLEANED_AFTER_RECONNECT', 
  'RNMO_RECENTLY_ADDED', 
  'RNMO_USER', 
  'RNMO_SUBSCRIPTIONS', 
  'RNMO_RECENTLY_ADDED_DOCUMENTS', 
  'RNMO_RECENTLY_CLEANED_COLLECTIONS'
];

export default packagePrivateReducers;